---
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
gitlab_urls:
  api: https://gitlab.oit.duke.edu/api/v4/
  download: https://gitlab.oit.duke.edu
  use_package_registry: true
  use_job_token: true
env:
  - VAULT_ADDR={{ .Env.VAULT_ADDR }}
  - TRANSIT_SECRET_ENGINE_PATH=ssi-systems/transit
  - VAULT_TOKEN={{ .Env.VAULT_TOKEN }}
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/suitcasectl
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags: |
      -s -w
      -X {{ .ModulePath }}/cmd/suitcasectl/cmd.date={{ .CommitTimestamp }}
      -X {{ .ModulePath }}/cmd/suitcasectl/cmd.version={{ .Tag }}
      -X {{ .ModulePath }}/cmd/suitcasectl/cmd.commit={{ .ShortCommit }}
    targets:
      - go_first_class
    binary: 'suitcasectl'
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-snapshot"
brews:
  - tap:
      owner: devil-ops
      name: homebrew-devil-ops
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    description: "Data Suitcase Suitcase Controller"
    name: "suitcasectl"
    homepage: https://gitlab.oit.duke.edu/devil-ops
    install: |
      bin.install "suitcasectl"
      bash_completion.install "completions/suitcasectl.bash" => "suitcasectl"
      zsh_completion.install "completions/suitcasectl.zsh" => "_suitcasectl"
      fish_completion.install "completions/suitcasectl.fish"
nfpms:
  - id: rpms
    license: MIT
    description: Package up research files for distribution
    vendor: Duke University
    section: admin
    priority: optional
    maintainer: Drew Stinnett <drew.stinnett@duke.edu>
    homepage: https://gitlab.oit.duke.edu/devil-ops/suitcasectl
    replaces:
      - data-suitcase
    rpm:
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"
    formats:
      - rpm
    contents:
      - src: ./completions/suitcasectl.bash
        dst: /usr/share/bash-completion/completions/suitcasectl
        file_info:
          mode: 0644
      - src: ./completions/suitcasectl.fish
        dst: /usr/share/fish/vendor_completions.d/suitcasectl.fish
        file_info:
          mode: 0644
      - src: ./completions/suitcasectl.zsh
        dst:  /usr/share/zsh/vendor-completions/_suitcasectl
        file_info:
          mode: 0644
  - id: debs
    license: MIT
    description: Package up research files for distribution
    vendor: Duke University
    section: admin
    priority: optional
    homepage: https://gitlab.oit.duke.edu/devil-ops/suitcasectl
    maintainer: Drew Stinnett <drew.stinnett@duke.edu>
    replaces:
      - data-suitcase
    formats:
      - deb
    contents:
      - src: ./completions/suitcasectl.bash
        dst: /usr/share/bash-completion/completions/suitcasectl
        file_info:
          mode: 0644
      - src: ./completions/suitcasectl.fish
        dst: /usr/share/fish/vendor_completions.d/suitcasectl.fish
        file_info:
          mode: 0644
      - src: ./completions/suitcasectl.zsh
        dst:  /usr/share/zsh/vendor-completions/_suitcasectl
        file_info:
          mode: 0644
uploads:
  - name: productionrpm
    target: https://oneget.oit.duke.edu/rpm/devil-ops-rpms/
    method: PUT
    mode: archive
    username: api
    ids:
      - rpms
  - name: productiondeb
    target: https://oneget.oit.duke.edu/debian-packages/upload/devil-ops-debs/main/
    method: PUT
    mode: archive
    username: api
    ids:
      - debs
signs:
- cmd: cosign
  args: ["sign-blob", "--key=hashivault://package-signing", "--output-signature=${signature}", "${artifact}"]
  artifacts: all
sboms:
  - artifacts: archive