---
gitlab_urls:
  api: https://gitlab.oit.duke.edu/api/v4/
  download: https://gitlab.oit.duke.edu
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cli
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags: |
      -s -w
      -X {{ .ModulePath }}/cli/cmd.date={{ .CommitTimestamp }}
      -X {{ .ModulePath }}/cli/cmd.version={{ .Tag }}
      -X {{ .ModulePath }}/cli/cmd.commit={{ .ShortCommit }}
    goos:
      - linux
    goarch:
      - amd64
    binary: 'suitcasectl'
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-snapshot"

nfpms:
  - id: rpms
    bindir: /usr/bin
    license: MIT
    description: Package up research files for distribution
    vendor: Duke University
    section: admin
    priority: optional
    homepage: https://gitlab.oit.duke.edu/oit-ssi-systems/data-suitcase
    maintainer: Drew Stinnett <drew.stinnett@duke.edu>
    formats:
      - rpm
  - id: debs
    bindir: /usr/bin
    license: MIT
    description: Package up research files for distribution
    vendor: Duke University
    section: admin
    priority: optional
    homepage: https://gitlab.oit.duke.edu/oit-ssi-systems/data-suitcase
    maintainer: Drew Stinnett <drew.stinnett@duke.edu>
    formats:
      - deb