package gpg

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/ProtonMail/gopenpgp/v2/crypto"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestNewKeyPair_PassphraseLocksPrivateKey pins the fix for #399.
//
// KeyOpts.Passphrase was declared but read nowhere in the repo: NewKeyPair
// generated a key and armored it without ever calling Lock(), so every private
// key this package produced was plaintext PGP key material. A struct field named
// Passphrase that does nothing is worse than no field at all, because it stops
// the reader from asking whether protection exists.
func TestNewKeyPair_PassphraseLocksPrivateKey(t *testing.T) {
	kp, err := NewKeyPair(&KeyOpts{
		Name:       "test",
		Email:      "test@example.com",
		KeyType:    "rsa",
		Bits:       1024,
		Passphrase: []byte("correct horse battery staple"),
	})
	require.NoError(t, err)

	key, err := crypto.NewKeyFromArmored(kp.Private)
	require.NoError(t, err)

	locked, err := key.IsLocked()
	require.NoError(t, err)
	assert.True(t, locked, "a passphrase must encrypt the private key at rest")

	// The passphrase must actually be the one required to open it.
	_, err = key.Unlock([]byte("correct horse battery staple"))
	assert.NoError(t, err, "the supplied passphrase must unlock the key")

	_, err = key.Unlock([]byte("wrong passphrase"))
	assert.Error(t, err, "a different passphrase must not unlock the key")
}

// TestNewKeyPair_PublicKeyStaysUsableWhenLocked guards the obvious way to get
// the fix wrong: locking the private key must not damage the public half, which
// is what recipients actually receive.
func TestNewKeyPair_PublicKeyStaysUsableWhenLocked(t *testing.T) {
	kp, err := NewKeyPair(&KeyOpts{
		Name:       "test",
		Email:      "test@example.com",
		KeyType:    "rsa",
		Bits:       1024,
		Passphrase: []byte("hunter2"),
	})
	require.NoError(t, err)

	pub, err := crypto.NewKeyFromArmored(kp.Public)
	require.NoError(t, err)
	assert.False(t, pub.IsPrivate(), "the public key must not carry private material")
	assert.True(t, pub.CanEncrypt(), "the public key must still be usable for encryption")
}

// TestNewKeyPair_NoPassphraseIsRefused makes the unsafe case explicit rather
// than default. Generating an unlocked long-lived private key is a deliberate
// choice, so it requires AllowUnprotected instead of just omitting a field.
func TestNewKeyPair_NoPassphraseIsRefused(t *testing.T) {
	_, err := NewKeyPair(&KeyOpts{
		Name:    "test",
		Email:   "test@example.com",
		KeyType: "rsa",
		Bits:    1024,
	})
	require.Error(t, err, "an unprotected key must not be generated by default")
	assert.ErrorIs(t, err, ErrNoPassphrase)
}

// TestNewKeyPair_AllowUnprotectedOptsOut confirms the escape hatch works, and
// that it produces exactly what it says: an unlocked key.
func TestNewKeyPair_AllowUnprotectedOptsOut(t *testing.T) {
	kp, err := NewKeyPair(&KeyOpts{
		Name:             "test",
		Email:            "test@example.com",
		KeyType:          "rsa",
		Bits:             1024,
		AllowUnprotected: true,
	})
	require.NoError(t, err)

	key, err := crypto.NewKeyFromArmored(kp.Private)
	require.NoError(t, err)
	locked, err := key.IsLocked()
	require.NoError(t, err)
	assert.False(t, locked, "AllowUnprotected must produce an unlocked key, as documented")
}

// TestNewKeyPair_PassphraseAndAllowUnprotectedConflict rejects a contradictory
// request instead of silently honouring one side. Which side a reader assumes
// wins is exactly the ambiguity that hides a missing lock.
func TestNewKeyPair_PassphraseAndAllowUnprotectedConflict(t *testing.T) {
	_, err := NewKeyPair(&KeyOpts{
		Name:             "test",
		Email:            "test@example.com",
		KeyType:          "rsa",
		Bits:             1024,
		Passphrase:       []byte("hunter2"),
		AllowUnprotected: true,
	})
	require.Error(t, err)
	assert.ErrorIs(t, err, ErrConflictingPassphrase)
}

// TestNewKeyFilesWithPair_DefaultsToWorkingDirectory pins the other half of
// #399: the default destination used to be os.MkdirTemp, which left private key
// material in $TMPDIR indefinitely. On the shared HPC systems CargoShip targets,
// $TMPDIR is frequently a shared filesystem subject to an undocumented reaper —
// so the key is both more exposed and less durable than the user expects.
func TestNewKeyFilesWithPair_DefaultsToWorkingDirectory(t *testing.T) {
	kp, err := NewKeyPair(&KeyOpts{
		Name:       "test",
		Email:      "test@example.com",
		KeyType:    "rsa",
		Bits:       1024,
		Passphrase: []byte("hunter2"),
	})
	require.NoError(t, err)

	// Isolate both the working directory and TMPDIR so the assertion below is
	// about behaviour, not about whatever else is on this machine.
	work := t.TempDir()
	tmp := t.TempDir()
	t.Setenv("TMPDIR", tmp)

	wd, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(work))
	t.Cleanup(func() { _ = os.Chdir(wd) })

	files, err := NewKeyFilesWithPair(kp, "")
	require.NoError(t, err)
	require.Len(t, files, 2)

	// Resolve symlinks: on darwin t.TempDir() lives under /var, itself a symlink
	// to /private/var, so a raw string compare against os.Getwd would fail.
	resolvedWork, err := filepath.EvalSymlinks(work)
	require.NoError(t, err)

	for _, f := range files {
		resolved, rerr := filepath.EvalSymlinks(f)
		require.NoError(t, rerr)
		assert.Equal(t, resolvedWork, filepath.Dir(resolved),
			"keys must land in the working directory, not a temp dir")
	}

	entries, err := os.ReadDir(tmp)
	require.NoError(t, err)
	assert.Empty(t, entries, "no private key material may be written to TMPDIR")
}

// TestNewKeyFilesWithPair_RefusesToOverwrite protects against the destructive
// consequence of writing to a predictable path: a second run in the same
// directory silently replacing a key the user still needs. Losing a private key
// is unrecoverable, so this fails loudly instead.
func TestNewKeyFilesWithPair_RefusesToOverwrite(t *testing.T) {
	kp, err := NewKeyPair(&KeyOpts{
		Name:       "test",
		Email:      "test@example.com",
		KeyType:    "rsa",
		Bits:       1024,
		Passphrase: []byte("hunter2"),
	})
	require.NoError(t, err)

	dir := t.TempDir()
	_, err = NewKeyFilesWithPair(kp, dir)
	require.NoError(t, err)

	original, err := os.ReadFile(filepath.Join(dir, "private.key"))
	require.NoError(t, err)

	_, err = NewKeyFilesWithPair(kp, dir)
	require.Error(t, err, "an existing key must not be silently overwritten")

	after, err := os.ReadFile(filepath.Join(dir, "private.key"))
	require.NoError(t, err)
	assert.Equal(t, original, after, "the existing private key must be left intact")
}

// TestNewKeyFilesWithPair_PrivateKeyIsNotWorldReadable asserts the mode bits,
// which were already correct — pinning them so a future refactor of the write
// path cannot loosen them unnoticed.
func TestNewKeyFilesWithPair_PrivateKeyIsNotWorldReadable(t *testing.T) {
	kp, err := NewKeyPair(&KeyOpts{
		Name:       "test",
		Email:      "test@example.com",
		KeyType:    "rsa",
		Bits:       1024,
		Passphrase: []byte("hunter2"),
	})
	require.NoError(t, err)

	dir := t.TempDir()
	files, err := NewKeyFilesWithPair(kp, dir)
	require.NoError(t, err)

	info, err := os.Stat(files[0])
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0o600), info.Mode().Perm(),
		"the private key must be readable only by its owner")
}
