//go:build e2e

// Cross-version archive readability (#322).
//
// The format spec promises manifest v2.0 with v1.0 still readable, and the
// maturity page tells users "your archives don't become unreadable on upgrade."
// Every other test in this repo writes and reads with the SAME build, which
// proves self-consistency — not backward readability, which is the property
// archival users actually depend on.
//
// So this file does two things:
//
//   - TestGenerateArchiveFixtures (opt-in, needs network + gh) drives ACTUAL
//     RELEASED BINARIES against the emulator and captures the S3 object trees
//     they write into testdata/archives/. Run via scripts/gen-archive-fixtures.sh.
//   - TestCrossVersionArchiveReadability (runs in CI) serves each committed
//     fixture back from the emulator and restores it with CURRENT code,
//     asserting byte-identical contents.
//
// The fixtures are generated by old binaries rather than reconstructed by the
// current writer on purpose: a reconstruction shares today's bugs and would pass
// vacuously. That is the whole reason this test can catch a format regression.
package e2e

import (
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

// archivesDir holds one subdirectory per captured release.
const archivesDir = "testdata/archives"

// layouts are the two shapes an upload can produce. Both are captured for every
// version because they are separate read paths in restore — a regression can hit
// one and not the other (as the chunked-URL-restore bug in the trust epic did).
var layouts = []string{"direct", "chunked"}

// fixtureManifest records what a captured archive is expected to contain, so the
// readability test can assert byte-identity without re-deriving it from the
// archive it is testing.
type fixtureManifest struct {
	Version     string        `json:"version"`      // CargoShip release that wrote it
	Layout      string        `json:"layout"`       // "direct" or "chunked"
	UploadID    string        `json:"upload_id"`    // the timestamped upload ID
	Prefix      string        `json:"prefix"`       // S3 prefix under the bucket
	ManifestKey string        `json:"manifest_key"` // key of the archive's own manifest
	Files       []fixtureFile `json:"files"`
}

// fixtureFile is one expected file in a captured archive.
//
// ManifestPath is the path string as the OLD binary recorded it in its manifest,
// captured verbatim from that manifest rather than assumed. Releases through
// v0.18.0 record an ABSOLUTE source path, so it embeds the temp directory that
// existed when the fixture was generated. That looks odd committed to the repo,
// but it is the honest artifact: `restore --file` matches against the manifest's
// own path, so this is the string that actually addresses the file. Deriving it
// instead of recording it would bake today's assumption about path shape into a
// test whose entire purpose is to notice when that shape changes.
type fixtureFile struct {
	ManifestPath string `json:"manifest_path"`
	Base         string `json:"base"`
	SHA256       string `json:"sha256"`
	Size         int64  `json:"size"`
}

// writerCorrupt marks version/layout combinations whose archives the WRITER of
// that release produced incorrectly. Backward readability cannot be asserted for
// them — the bytes are not in the object, so no reader could return them.
//
// v0.14.0 and v0.15.0 shipped #275: the archiver closed its pipe in the wrong
// order, the final zstd frame was never flushed, and the last file in every
// compressed chunk was truncated. Fixed in v0.16.0. Reading their chunk tars
// confirms it — the last entry ends in `unexpected EOF` while v0.16.1+ read
// clean.
//
// These fixtures are KEPT rather than dropped, and still tested: see
// TestCrossVersionKnownCorruptArchivesAreNotSilentlyAccepted. An archival tool's
// behavior on a corrupt archive it wrote itself is worth pinning, and a fixture
// generated by the real buggy binary is the only honest way to pin it.
var writerCorrupt = map[string]string{
	"v0.14.0/chunked": "#275: unflushed final zstd frame truncates the last file in each chunk",
	"v0.15.0/chunked": "#275: unflushed final zstd frame truncates the last file in each chunk",
}

// --- the readability test (runs in CI) --------------------------------------

// TestCrossVersionArchiveReadability restores every committed fixture with the
// CURRENT build and asserts the bytes come back identical.
//
// This is the check that would catch a format regression before a user with a
// three-year-old archive does.
func TestCrossVersionArchiveReadability(t *testing.T) {
	versions := committedFixtureVersions(t)
	if len(versions) == 0 {
		t.Fatalf("no archive fixtures under %s — run scripts/gen-archive-fixtures.sh", archivesDir)
	}
	t.Logf("testing %d committed archive fixture set(s): %v", len(versions), versions)

	for _, version := range versions {
		for _, layout := range layouts {
			dir := filepath.Join(archivesDir, version, layout)
			if _, err := os.Stat(dir); err != nil {
				continue // that version/layout combination wasn't captured
			}

			if reason, corrupt := writerCorrupt[version+"/"+layout]; corrupt {
				t.Logf("skipping %s/%s readability: archive is writer-corrupt (%s); covered by TestCrossVersionKnownCorruptArchivesAreNotSilentlyAccepted",
					version, layout, reason)
				continue
			}

			t.Run(version+"/"+layout, func(t *testing.T) {
				fm := loadFixtureManifest(t, dir)

				// Serve the captured object tree back under the bucket name the
				// archive's OWN manifest records — not an arbitrary fresh one.
				// Restore resolves each object against `manifest.Bucket` rather
				// than the bucket in the URL it was given (#334), so replaying
				// elsewhere would fail for a reason that has nothing to do with
				// the format. Read from the archive instead of stored in
				// fixture.json so it cannot drift from the bytes it describes.
				bucket := fixtureArchiveBucket(t, dir, fm)
				if err := createBucket(substrateURL, bucket); err != nil {
					t.Fatalf("create bucket: %v", err)
				}
				restoreObjectTree(t, bucket, dir)

				uploadURL := fmt.Sprintf("s3://%s/%s/uploads/%s", bucket, fm.Prefix, fm.UploadID)

				// 1. verify must accept an archive written by the old release.
				// It exits non-zero on any integrity failure, so a format
				// misread shows up here even before we look at bytes.
				runCargoship(t, "verify", uploadURL, "--region", "us-east-1")

				if len(fm.Files) == 0 {
					t.Fatalf("fixture %s records no files; it cannot prove anything", dir)
				}

				// 2. Restore every recorded file and compare byte-for-byte.
				// Paths come from the fixture (restore has no --all) and are the
				// strings the OLD release put in its manifest.
				restoreDir := t.TempDir()
				args := []string{"restore", uploadURL, restoreDir, "--region", "us-east-1"}
				for _, f := range fm.Files {
					args = append(args, "--file", f.ManifestPath)
				}
				runCargoship(t, args...)

				for _, f := range fm.Files {
					got, err := os.ReadFile(findFileByBase(t, restoreDir, f.Base))
					if err != nil {
						t.Fatalf("%s: restored file missing: %v", f.ManifestPath, err)
					}
					sum := sha256.Sum256(got)
					if gotDigest := hex.EncodeToString(sum[:]); gotDigest != f.SHA256 {
						t.Errorf("%s: content changed across versions\n got sha256 %s (%d bytes)\nwant sha256 %s (%d bytes)",
							f.ManifestPath, gotDigest, len(got), f.SHA256, f.Size)
						continue
					}
					t.Logf("✅ %s (%d bytes) restored byte-identically from %s", f.Base, len(got), version)
				}
			})
		}
	}
}

// TestCrossVersionKnownCorruptArchivesAreNotSilentlyAccepted covers the
// writer-corrupt fixtures — archives real released binaries produced wrong.
//
// The bytes are not in the object, so no reader can return them. What CAN be
// asserted, and matters more, is that current code does not hand a user a file
// that looks complete and is not. A short file with a success exit code is worse
// than a loud failure, because the user deletes their source afterward.
//
// It is what found #337 and #336. The unverified extract path used io.Copy, for
// which a truncated tar entry is indistinguishable from EOF, so it wrote the
// short file and reported success — and the command exited 0 while printing
// "Files failed: 2" beside it. These v0.14.0/v0.15.0 manifests record no
// per-file checksums (they predate #270), which is exactly why they took the
// unverified path: the archives most likely to be truncated were the ones on the
// one code path that could not notice. The two defects line up.
func TestCrossVersionKnownCorruptArchivesAreNotSilentlyAccepted(t *testing.T) {
	for key, reason := range writerCorrupt {
		version, layout, ok := strings.Cut(key, "/")
		if !ok {
			t.Fatalf("malformed writerCorrupt key %q", key)
		}
		dir := filepath.Join(archivesDir, version, layout)
		if _, err := os.Stat(dir); err != nil {
			continue
		}

		t.Run(key, func(t *testing.T) {
			t.Logf("archive is known writer-corrupt: %s", reason)
			fm := loadFixtureManifest(t, dir)

			bucket := fixtureArchiveBucket(t, dir, fm)
			if err := createBucket(substrateURL, bucket); err != nil {
				t.Fatalf("create bucket: %v", err)
			}
			restoreObjectTree(t, bucket, dir)
			uploadURL := fmt.Sprintf("s3://%s/%s/uploads/%s", bucket, fm.Prefix, fm.UploadID)

			// verify --deep must refuse to certify an archive it cannot check.
			// These manifests record no checksum algorithm, so the honest answer
			// is "unverifiable", not "OK". This part passes today.
			out, err := exec.Command(cargoshipBin, "verify", uploadURL,
				"--deep", "--region", "us-east-1").CombinedOutput()
			if err == nil {
				t.Errorf("verify --deep exited 0 on an unverifiable archive; it must not certify what it cannot check\n%s", out)
			}
			if !bytes.Contains(out, []byte("unverifiable")) && !bytes.Contains(out, []byte("UNVERIFIABLE")) {
				t.Errorf("verify --deep did not report the archive as unverifiable\n%s", out)
			}

			// Restore must not leave a file whose size contradicts the manifest.
			restoreDir := t.TempDir()
			args := []string{"restore", uploadURL, restoreDir, "--region", "us-east-1"}
			for _, f := range fm.Files {
				args = append(args, "--file", f.ManifestPath)
			}
			restoreOut, restoreErr := exec.Command(cargoshipBin, args...).CombinedOutput()

			for _, f := range fm.Files {
				path := findFileByBaseOrEmpty(restoreDir, f.Base)
				if path == "" {
					continue // absent is the correct outcome for a truncated entry
				}
				info, statErr := os.Stat(path)
				if statErr != nil {
					t.Fatalf("stat %s: %v", path, statErr)
				}
				if info.Size() != f.Size {
					t.Errorf("restore left a TRUNCATED %s on disk: %d bytes, manifest says %d (#337)\n%s",
						f.Base, info.Size(), f.Size, restoreOut)
				}
			}

			// A restore that could not produce every requested file must say so
			// in its exit code, not only in its printed summary (#336).
			if restoreErr == nil && bytes.Contains(restoreOut, []byte("Files failed:")) {
				t.Errorf("restore reported failed files but exited 0 (#336)\n%s", restoreOut)
			}
		})
	}
}

// TestCrossVersionFixtureCoverage keeps the fixture corpus honest.
//
// The guarantee is only as old as the oldest fixture, so a corpus that quietly
// stops growing is a guarantee that quietly stops covering recent releases. This
// asserts the released versions the CHANGELOG knows about are represented, from
// the first version fixtures exist for onward.
func TestCrossVersionFixtureCoverage(t *testing.T) {
	have := map[string]bool{}
	for _, v := range committedFixtureVersions(t) {
		have[v] = true
	}
	if len(have) == 0 {
		t.Fatalf("no archive fixtures under %s", archivesDir)
	}

	// Both layouts, for every captured version — a version present in only one
	// layout leaves the other read path unguarded for that release.
	for v := range have {
		for _, layout := range layouts {
			dir := filepath.Join(archivesDir, v, layout)
			if _, err := os.Stat(dir); err != nil {
				t.Errorf("%s: missing the %q layout; both read paths must be covered", v, layout)
			}
		}
	}
}

// --- fixture generation (opt-in) --------------------------------------------

// TestGenerateArchiveFixtures captures archives from released binaries. It skips
// unless scripts/gen-archive-fixtures.sh has staged the binaries and named the
// versions, so a normal `go test -tags e2e` run never tries to reach the network.
func TestGenerateArchiveFixtures(t *testing.T) {
	binDir := os.Getenv("CARGOSHIP_FIXTURE_BINDIR")
	versionList := os.Getenv("CARGOSHIP_FIXTURE_VERSIONS")
	if binDir == "" || versionList == "" {
		t.Skip("fixture generation is opt-in; run scripts/gen-archive-fixtures.sh")
	}

	for _, version := range strings.Fields(versionList) {
		bin := filepath.Join(binDir, version, "cargoship")
		if _, err := os.Stat(bin); err != nil {
			t.Fatalf("%s: binary not staged at %s: %v", version, bin, err)
		}

		for _, layout := range layouts {
			t.Run(version+"/"+layout, func(t *testing.T) {
				generateFixture(t, version, layout, bin)
			})
		}
	}
}

// generateFixture runs one released binary against the emulator and copies the
// resulting object tree into testdata/.
func generateFixture(t *testing.T, version, layout, bin string) {
	t.Helper()

	bucket := fmt.Sprintf("gen-%s-%s", strings.ReplaceAll(version, ".", "-"), layout)
	if err := createBucket(substrateURL, bucket); err != nil {
		t.Fatalf("create bucket: %v", err)
	}
	const prefix = "archives"

	src := t.TempDir()
	files := fixtureSourceFiles(t, src, layout)

	// Note deliberately NOT passed: --direct-upload-threshold-mb. Older releases
	// accepted that flag and ignored it (the #316 no-op-flag bug), so layout is
	// chosen by DATA SHAPE — file sizes that fall on either side of the
	// direct-upload heuristic — which every version honors.
	args := []string{"upload", src, fmt.Sprintf("s3://%s/%s", bucket, prefix),
		"--region", "us-east-1", "--shard-count", "2"}
	cmd := exec.Command(bin, args...)
	cmd.Env = os.Environ()
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("%s upload failed: %v\n%s", version, err, out)
	}

	// Confirm the binary actually took the layout we intended. Asserting this is
	// the difference between "two fixtures" and "the same fixture twice".
	usedDirect := bytes.Contains(out, []byte("direct upload mode"))
	if (layout == "direct") != usedDirect {
		t.Fatalf("%s: wanted %s layout but binary used direct=%v\n%s", version, layout, usedDirect, out)
	}

	uploadID := extractUploadID(t, string(out))
	manifestKey := fmt.Sprintf("%s/uploads/%s/manifest.json.gz", prefix, uploadID)

	// Read the path strings back out of the archive's OWN manifest rather than
	// assuming their shape. `restore --file` matches against these, and older
	// releases record absolute source paths — an assumption here would silently
	// address nothing.
	recorded := manifestFilePaths(t, bucket, manifestKey)
	if len(recorded) != len(files) {
		t.Fatalf("%s/%s: manifest lists %d files, wrote %d", version, layout, len(recorded), len(files))
	}

	fm := fixtureManifest{
		Version:     version,
		Layout:      layout,
		UploadID:    uploadID,
		Prefix:      prefix,
		ManifestKey: manifestKey,
	}
	for _, mp := range recorded {
		base := path.Base(mp)
		content, ok := files[base]
		if !ok {
			t.Fatalf("%s/%s: manifest names %q, which we never wrote", version, layout, mp)
		}
		sum := sha256.Sum256(content)
		fm.Files = append(fm.Files, fixtureFile{
			ManifestPath: mp,
			Base:         base,
			SHA256:       hex.EncodeToString(sum[:]),
			Size:         int64(len(content)),
		})
	}
	sort.Slice(fm.Files, func(i, j int) bool { return fm.Files[i].Base < fm.Files[j].Base })

	dir := filepath.Join(archivesDir, version, layout)
	if err := os.RemoveAll(dir); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	captureObjectTree(t, bucket, dir)
	writeFixtureManifest(t, dir, fm)

	t.Logf("captured %s/%s → %s (upload %s)", version, layout, dir, uploadID)
}

// fixtureSourceFiles writes the source tree for a fixture and returns the exact
// bytes written, keyed by name.
//
// Content is deterministic (a fixed byte pattern, no randomness) so regenerating
// a version's fixture produces identical source data and the diff shows only
// what the writer actually changed.
func fixtureSourceFiles(t *testing.T, dir, layout string) map[string][]byte {
	t.Helper()

	pattern := func(n int, seed byte) []byte {
		b := make([]byte, n)
		for i := range b {
			b[i] = byte((i*31 + int(seed)) % 251)
		}
		return b
	}

	files := map[string][]byte{}
	switch layout {
	case "direct":
		// Small files with a small average size take the direct-upload fast path.
		files["notes.txt"] = []byte("cross-version fixture: plain text\n")
		files["data.bin"] = pattern(4096, 7)
	case "chunked":
		// Average file size >= 5 MB defeats the direct-upload heuristic in every
		// release, so these land in the sharded tar.zst layout. The pattern
		// compresses hard, so the committed fixture stays a couple of KB.
		files["big-a.bin"] = pattern(6*1024*1024, 11)
		files["big-b.bin"] = pattern(6*1024*1024, 23)
	default:
		t.Fatalf("unknown layout %q", layout)
	}

	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), content, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return files
}

// --- object-tree capture and replay -----------------------------------------

func fixtureS3Client() *s3.Client {
	cfg := aws.Config{
		Region:       "us-east-1",
		BaseEndpoint: aws.String(substrateURL),
		Credentials:  credentials.NewStaticCredentialsProvider("test", "test", ""),
	}
	return s3.NewFromConfig(cfg, func(o *s3.Options) { o.UsePathStyle = true })
}

// captureObjectTree copies every object in bucket to dir, preserving key paths
// so the tree can be replayed verbatim later.
func captureObjectTree(t *testing.T, bucket, dir string) {
	t.Helper()
	ctx := context.Background()
	client := fixtureS3Client()

	var token *string
	for {
		page, err := client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{
			Bucket:            aws.String(bucket),
			ContinuationToken: token,
		})
		if err != nil {
			t.Fatalf("list %s: %v", bucket, err)
		}
		for _, obj := range page.Contents {
			key := aws.ToString(obj.Key)
			body, err := client.GetObject(ctx, &s3.GetObjectInput{
				Bucket: aws.String(bucket),
				Key:    aws.String(key),
			})
			if err != nil {
				t.Fatalf("get %s: %v", key, err)
			}
			data := readAllAndClose(t, body)

			// The upload ID is part of the key, so keys are stored relative to
			// the bucket root and replayed as-is.
			dest := filepath.Join(dir, "objects", filepath.FromSlash(key))
			if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(dest, data, 0o644); err != nil {
				t.Fatal(err)
			}
		}
		if page.IsTruncated == nil || !*page.IsTruncated {
			break
		}
		token = page.NextContinuationToken
	}
}

// restoreObjectTree uploads a captured tree back into bucket under its original
// keys, so current code sees byte-for-byte what the old release wrote.
func restoreObjectTree(t *testing.T, bucket, dir string) {
	t.Helper()
	ctx := context.Background()
	client := fixtureS3Client()
	root := filepath.Join(dir, "objects")

	count := 0
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		_, putErr := client.PutObject(ctx, &s3.PutObjectInput{
			Bucket: aws.String(bucket),
			Key:    aws.String(filepath.ToSlash(rel)),
			Body:   bytes.NewReader(data),
		})
		if putErr != nil {
			return fmt.Errorf("put %s: %w", rel, putErr)
		}
		count++
		return nil
	})
	if err != nil {
		t.Fatalf("replay object tree from %s: %v", dir, err)
	}
	if count == 0 {
		t.Fatalf("fixture %s contains no objects", root)
	}
}

// --- small helpers ----------------------------------------------------------

// committedFixtureVersions lists the versions with fixtures on disk, sorted so
// test output is stable.
func committedFixtureVersions(t *testing.T) []string {
	t.Helper()
	entries, err := os.ReadDir(archivesDir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		t.Fatalf("read %s: %v", archivesDir, err)
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() && strings.HasPrefix(e.Name(), "v") {
			out = append(out, e.Name())
		}
	}
	sort.Strings(out)
	return out
}

// archiveManifest is the subset of an archive's own manifest this test reads.
//
// Deliberately a narrow local type rather than pkg/manifest.Manifest: this test
// asserts what OLD releases wrote, and unmarshalling into today's structs would
// launder away any field the current type no longer models — the exact drift it
// exists to notice.
type archiveManifest struct {
	Bucket string `json:"bucket"`
	Files  []struct {
		Path string `json:"path"`
	} `json:"files"`
}

// parseArchiveManifest decodes a manifest body, gunzipping it when key names a
// .gz object.
func parseArchiveManifest(t *testing.T, key string, raw []byte) archiveManifest {
	t.Helper()

	if strings.HasSuffix(key, ".gz") {
		zr, err := gzip.NewReader(bytes.NewReader(raw))
		if err != nil {
			t.Fatalf("gunzip manifest %s: %v", key, err)
		}
		defer func() { _ = zr.Close() }()
		raw, err = io.ReadAll(zr)
		if err != nil {
			t.Fatalf("read gzipped manifest %s: %v", key, err)
		}
	}

	var doc archiveManifest
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse manifest %s: %v", key, err)
	}
	return doc
}

// manifestFilePaths fetches the archive's own manifest from S3 and returns the
// `path` field of each file entry, exactly as the writing release recorded it.
func manifestFilePaths(t *testing.T, bucket, key string) []string {
	t.Helper()

	obj, err := fixtureS3Client().GetObject(context.Background(), &s3.GetObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	})
	if err != nil {
		t.Fatalf("get manifest %s: %v", key, err)
	}
	doc := parseArchiveManifest(t, key, readAllAndClose(t, obj))

	paths := make([]string, 0, len(doc.Files))
	for _, f := range doc.Files {
		paths = append(paths, f.Path)
	}
	return paths
}

// findFileByBaseOrEmpty is findFileByBase without the t.Fatalf: it returns "" when
// nothing matches, for callers where an absent file is a legitimate outcome.
func findFileByBaseOrEmpty(dir, base string) string {
	var found string
	_ = filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if !info.IsDir() && filepath.Base(path) == base {
			found = path
		}
		return nil
	})
	return found
}

// fixtureArchiveBucket reads the bucket name out of the committed archive's own
// manifest — the bucket restore will actually address objects in (#334).
func fixtureArchiveBucket(t *testing.T, dir string, fm fixtureManifest) string {
	t.Helper()

	path := filepath.Join(dir, "objects", filepath.FromSlash(fm.ManifestKey))
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read archive manifest %s: %v", path, err)
	}
	doc := parseArchiveManifest(t, fm.ManifestKey, raw)
	if doc.Bucket == "" {
		t.Fatalf("archive manifest %s records no bucket", path)
	}
	return doc.Bucket
}

// readAllAndClose drains a GetObject body and closes it.
func readAllAndClose(t *testing.T, out *s3.GetObjectOutput) []byte {
	t.Helper()
	defer func() { _ = out.Body.Close() }()
	data, err := io.ReadAll(out.Body)
	if err != nil {
		t.Fatalf("read object body: %v", err)
	}
	return data
}

func loadFixtureManifest(t *testing.T, dir string) fixtureManifest {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, "fixture.json"))
	if err != nil {
		t.Fatalf("read fixture manifest in %s: %v", dir, err)
	}
	var fm fixtureManifest
	if err := json.Unmarshal(data, &fm); err != nil {
		t.Fatalf("parse fixture manifest in %s: %v", dir, err)
	}
	return fm
}

func writeFixtureManifest(t *testing.T, dir string, fm fixtureManifest) {
	t.Helper()
	data, err := json.MarshalIndent(fm, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "fixture.json"), append(data, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
}
