# VHS documentation
# Display:
#   Hide                            Hide the subsequent commands from the output
#   Show                            Show the subsequent commands in the output

Output wizard.gif

Require echo


Set Shell "bash"
Set FontSize 16
Set Width 1200
Set Height 700

Type "suitcasectl wizard" Sleep 500ms Enter
Sleep 2s
Type "~/Desktop/example-suitcase"
Tab
Backspace 5
Type "300Gb"
Sleep 1s
Tab
Sleep 1s
Tab
Sleep 1s
Tab

Sleep 5s
