// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package inventory

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	fs "io/fs"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory(in *jlexer.Lexer, out *InventoryFile) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Path":
			out.Path = string(in.String())
		case "Destination":
			out.Destination = string(in.String())
		case "Name":
			out.Name = string(in.String())
		case "Size":
			out.Size = int64(in.Int64())
		case "Mode":
			out.Mode = fs.FileMode(in.Uint32())
		case "ModTime":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ModTime).UnmarshalJSON(data))
			}
		case "IsDir":
			out.IsDir = bool(in.Bool())
		case "SHA256":
			out.SHA256 = string(in.String())
		case "Encrypt":
			out.Encrypt = bool(in.Bool())
		case "SuitcaseIndex":
			out.SuitcaseIndex = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory(out *jwriter.Writer, in InventoryFile) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Path\":"
		out.RawString(prefix[1:])
		out.String(string(in.Path))
	}
	{
		const prefix string = ",\"Destination\":"
		out.RawString(prefix)
		out.String(string(in.Destination))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Size\":"
		out.RawString(prefix)
		out.Int64(int64(in.Size))
	}
	{
		const prefix string = ",\"Mode\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Mode))
	}
	{
		const prefix string = ",\"ModTime\":"
		out.RawString(prefix)
		out.Raw((in.ModTime).MarshalJSON())
	}
	{
		const prefix string = ",\"IsDir\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDir))
	}
	{
		const prefix string = ",\"SHA256\":"
		out.RawString(prefix)
		out.String(string(in.SHA256))
	}
	{
		const prefix string = ",\"Encrypt\":"
		out.RawString(prefix)
		out.Bool(bool(in.Encrypt))
	}
	{
		const prefix string = ",\"SuitcaseIndex\":"
		out.RawString(prefix)
		out.Int(int(in.SuitcaseIndex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InventoryFile) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InventoryFile) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InventoryFile) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InventoryFile) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory(l, v)
}
func easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory1(in *jlexer.Lexer, out *IndexSummary) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Count":
			out.Count = uint(in.Uint())
		case "Size":
			out.Size = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory1(out *jwriter.Writer, in IndexSummary) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Count\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.Count))
	}
	{
		const prefix string = ",\"Size\":"
		out.RawString(prefix)
		out.Int64(int64(in.Size))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IndexSummary) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IndexSummary) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IndexSummary) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IndexSummary) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory1(l, v)
}
func easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory2(in *jlexer.Lexer, out *FileBucket) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Free":
			out.Free = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory2(out *jwriter.Writer, in FileBucket) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Free\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Free))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FileBucket) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FileBucket) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FileBucket) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FileBucket) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory2(l, v)
}
func easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory3(in *jlexer.Lexer, out *DirectoryInventoryOptions) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Name":
			out.Name = string(in.String())
		case "TopLevelDirectories":
			if in.IsNull() {
				in.Skip()
				out.TopLevelDirectories = nil
			} else {
				in.Delim('[')
				if out.TopLevelDirectories == nil {
					if !in.IsDelim(']') {
						out.TopLevelDirectories = make([]string, 0, 4)
					} else {
						out.TopLevelDirectories = []string{}
					}
				} else {
					out.TopLevelDirectories = (out.TopLevelDirectories)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.TopLevelDirectories = append(out.TopLevelDirectories, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "SizeConsideredLarge":
			out.SizeConsideredLarge = int64(in.Int64())
		case "MaxSuitcaseSize":
			out.MaxSuitcaseSize = int64(in.Int64())
		case "InternalMetadataGlob":
			out.InternalMetadataGlob = string(in.String())
		case "ExternalMetadataFiles":
			if in.IsNull() {
				in.Skip()
				out.ExternalMetadataFiles = nil
			} else {
				in.Delim('[')
				if out.ExternalMetadataFiles == nil {
					if !in.IsDelim(']') {
						out.ExternalMetadataFiles = make([]string, 0, 4)
					} else {
						out.ExternalMetadataFiles = []string{}
					}
				} else {
					out.ExternalMetadataFiles = (out.ExternalMetadataFiles)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.ExternalMetadataFiles = append(out.ExternalMetadataFiles, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "EncryptInner":
			out.EncryptInner = bool(in.Bool())
		case "HashInner":
			out.HashInner = bool(in.Bool())
		case "LimitFileCount":
			out.LimitFileCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory3(out *jwriter.Writer, in DirectoryInventoryOptions) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"TopLevelDirectories\":"
		out.RawString(prefix)
		if in.TopLevelDirectories == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.TopLevelDirectories {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"SizeConsideredLarge\":"
		out.RawString(prefix)
		out.Int64(int64(in.SizeConsideredLarge))
	}
	{
		const prefix string = ",\"MaxSuitcaseSize\":"
		out.RawString(prefix)
		out.Int64(int64(in.MaxSuitcaseSize))
	}
	{
		const prefix string = ",\"InternalMetadataGlob\":"
		out.RawString(prefix)
		out.String(string(in.InternalMetadataGlob))
	}
	{
		const prefix string = ",\"ExternalMetadataFiles\":"
		out.RawString(prefix)
		if in.ExternalMetadataFiles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.ExternalMetadataFiles {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"EncryptInner\":"
		out.RawString(prefix)
		out.Bool(bool(in.EncryptInner))
	}
	{
		const prefix string = ",\"HashInner\":"
		out.RawString(prefix)
		out.Bool(bool(in.HashInner))
	}
	{
		const prefix string = ",\"LimitFileCount\":"
		out.RawString(prefix)
		out.Int(int(in.LimitFileCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DirectoryInventoryOptions) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DirectoryInventoryOptions) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DirectoryInventoryOptions) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DirectoryInventoryOptions) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory3(l, v)
}
func easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory4(in *jlexer.Lexer, out *DirectoryInventory) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Files":
			if in.IsNull() {
				in.Skip()
				out.Files = nil
			} else {
				in.Delim('[')
				if out.Files == nil {
					if !in.IsDelim(']') {
						out.Files = make([]*InventoryFile, 0, 8)
					} else {
						out.Files = []*InventoryFile{}
					}
				} else {
					out.Files = (out.Files)[:0]
				}
				for !in.IsDelim(']') {
					var v7 *InventoryFile
					if in.IsNull() {
						in.Skip()
						v7 = nil
					} else {
						if v7 == nil {
							v7 = new(InventoryFile)
						}
						(*v7).UnmarshalEasyJSON(in)
					}
					out.Files = append(out.Files, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Options":
			if in.IsNull() {
				in.Skip()
				out.Options = nil
			} else {
				if out.Options == nil {
					out.Options = new(DirectoryInventoryOptions)
				}
				(*out.Options).UnmarshalEasyJSON(in)
			}
		case "TotalIndexes":
			out.TotalIndexes = int(in.Int())
		case "IndexSummaries":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.IndexSummaries = make(map[int]*IndexSummary)
				for !in.IsDelim('}') {
					key := int(in.IntStr())
					in.WantColon()
					var v8 *IndexSummary
					if in.IsNull() {
						in.Skip()
						v8 = nil
					} else {
						if v8 == nil {
							v8 = new(IndexSummary)
						}
						(*v8).UnmarshalEasyJSON(in)
					}
					(out.IndexSummaries)[key] = v8
					in.WantComma()
				}
				in.Delim('}')
			}
		case "InternalMetadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.InternalMetadata = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v9 string
					v9 = string(in.String())
					(out.InternalMetadata)[key] = v9
					in.WantComma()
				}
				in.Delim('}')
			}
		case "ExternalMetadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ExternalMetadata = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v10 string
					v10 = string(in.String())
					(out.ExternalMetadata)[key] = v10
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory4(out *jwriter.Writer, in DirectoryInventory) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Files\":"
		out.RawString(prefix[1:])
		if in.Files == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Files {
				if v11 > 0 {
					out.RawByte(',')
				}
				if v12 == nil {
					out.RawString("null")
				} else {
					(*v12).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Options\":"
		out.RawString(prefix)
		if in.Options == nil {
			out.RawString("null")
		} else {
			(*in.Options).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"TotalIndexes\":"
		out.RawString(prefix)
		out.Int(int(in.TotalIndexes))
	}
	{
		const prefix string = ",\"IndexSummaries\":"
		out.RawString(prefix)
		if in.IndexSummaries == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v13First := true
			for v13Name, v13Value := range in.IndexSummaries {
				if v13First {
					v13First = false
				} else {
					out.RawByte(',')
				}
				out.IntStr(int(v13Name))
				out.RawByte(':')
				if v13Value == nil {
					out.RawString("null")
				} else {
					(*v13Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"InternalMetadata\":"
		out.RawString(prefix)
		if in.InternalMetadata == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v14First := true
			for v14Name, v14Value := range in.InternalMetadata {
				if v14First {
					v14First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v14Name))
				out.RawByte(':')
				out.String(string(v14Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"ExternalMetadata\":"
		out.RawString(prefix)
		if in.ExternalMetadata == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v15First := true
			for v15Name, v15Value := range in.ExternalMetadata {
				if v15First {
					v15First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v15Name))
				out.RawByte(':')
				out.String(string(v15Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DirectoryInventory) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DirectoryInventory) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6f8bf452EncodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DirectoryInventory) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DirectoryInventory) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6f8bf452DecodeGitlabOitDukeEduOitSsiSystemsDataSuitcasePkgInventory4(l, v)
}
